### ISSUE TITLE
feasibility check technicians (route.h)

### ISSUE THREAD

**Issue by michieluithetbroek** [michieluithetbroek/mrs#14]
In the Route class we can store the used technicians for each location.
This will be used to check whether it is feasible to insert a new job in the route.
Now we use a loop which equals O(n).

**Comment by albert1991** [comment]
Dit is niet zo makkelijk als het lijkt. Plek van insertion bepaald namelijk of er wel of niet extra technicians gebruikt moeten worden.

**Comment by albert1991** [comment]
Done
