### ISSUE TITLE
Find most expensive pair

### ISSUE THREAD

**Issue by michieluithetbroek** [michieluithetbroek/mrs#38]
The function Route::find_exp() only checks for distance costs.
Also technician costs should be included.

Ook graag deze hele functie checken, is snel geschreven.

**Comment by albert1991** [comment]
Deze functie bestaat nog neit?

**Comment by michieluithetbroek** [comment]
jawel, nog niet gepushed

**Comment by albert1991** [comment]
dan doe ik niks daarmee :)

**Comment by albert1991** [comment]
hij gaat al behoorlijk steady naar 51999 K

**Comment by albert1991** [comment]
Verkeerde knopjes. sorry:(

**Comment by albert1991** [comment]
fixed
